### ISSUE TITLE
Invalid authorization is not detected

### ISSUE THREAD

**Issue by szuliq** [martensson/nixy#10]
When `nixy` is configured with invalid credentials it doesn't issue error messages as it should but instead operates happily with an empty set of apps/tasks.

**Comment by martensson** [comment]
Thanks for catching that, it should definitely be fixed and throw an error. 
I will look into it!

**Comment by martensson** [comment]
@szuliq I am trying to replicate the error you have here but not sure what error you expect.
Nixy should put the endpoint as sick after a few seconds if the status respond is 401. 
You should also get a bunch of "error reading Marathon event stream" before selecting the next available endpoint.

Maybe you are looking for a different error message?

**Comment by szuliq** [comment]
Hmm. I think nothing was reported when I stumbled upon that. I will try to reproduce it.

**Comment by martensson** [comment]
Closing this issue for now, please tell me if you manage to reproduce it again!
