### ISSUE TITLE
Optimize loop in syncApp

### ISSUE THREAD

**Issue by mlowicki** [martensson/nixy#12]
Currently code looks like:

```
    for _, app := range jsonapps.Apps {
    OUTER:
        for _, task := range jsontasks.Tasks {
            if task.AppId != app.Id {
                continue
            }
```

So list of tasks is iterated through many times (as many as number of apps). The idea is to first iterate over list of tasks and create map `appIdToTasks`. Then iterate over list of apps and get appropriate value from `appIdToTasks`. This way complexity from O(len(apps) \* len(tasks)) will be improved to O(len(tasks)) + O(len(apps)).

**Comment by martensson** [comment]
Thanks @mlowicki! 
I will look into this to refactor the code a bit. I will leave the issue open for now.

**Comment by martensson** [comment]
Fixed in latest commit, new release soon!
