### ISSUE TITLE
Suggestions for same hostname multiple path(s)

### ISSUE THREAD

**Issue by kholloway** [martensson/nixy#20]
Just wondering if you might have any template examples that support URL/path based routing for different apps sharing the same DNS/Hostname? With my current template Nginx refuses to start because I end up with many server blocks that have the same hostname.

I'm currently running Marathon-lb but am investigating using Nixy/Nginx. We route many microservices for the same Hostname to different paths (/common/ms1, /common/ms2, etc) which is achievable with MLB by assigning apps the same VHOST label with different PATH labels for the path routing.

That would require generating a single server block shared by many apps with multiple location blocks routing to each app in marathon.

Any suggestions/pointers would be greatly appreciated, thanks!

**Comment by martensson** [comment]
Hi @kholloway, let me take a look and come back about that. Should not be that hard to fix :)

**Comment by martensson** [comment]
You can now take a look at https://github.com/martensson/nixy/blob/master/nginx-path.tmpl

**Comment by kholloway** [comment]
Ahh nice trick with the servername, didn't realize you could do that with Nginx.

That covers most of my uses cases with one exception. Two different apps with same URL path but different host names. As long as my paths are all different then this config doesn't really care about my host name. 

Thanks!

**Comment by martensson** [comment]
Mixed path and host based config makes things a bit more tricky, but not impossible. The nice thing with using templates and nginx is the endless possibilities it gives ;)

**Comment by kholloway** [comment]
Very true! Thanks again!!
