### ISSUE TITLE
feature request: support "discovery"

### ISSUE THREAD

**Issue by jejer** [martensson/nixy#22]
Currently ports in ipAddress/discovery/ports not supported
```
{
  "id": "nginx-mesos",
  "container": {
    "type": "MESOS",
    "docker": {
      "image": "nginx:1.10.2-alpine"
    }
  },
  "cpus": 0.5,
  "mem": 64.0,
  "ipAddress": {
    "networkName": "calico-network",
    "labels": {
      "app": "nginx",
      "group": "production"
    },
    "discovery": {
      "ports": [
        { "number": 80, "name": "http", "protocol": "tcp" }
      ]
    }
  }
}
```

And portDefinitions is not available in ip-per-container mode.

**Comment by jejer** [comment]
I made a [fork](https://github.com/jejer/nixy) to make it work. 
But no plan to merge back because Unified containerizer/Marathon is working on [portMappings](https://github.com/mesosphere/marathon/issues/4548).
I think after it's done, we should use port mappings to declare service expose.

**Comment by martensson** [comment]
Thanks @jejer for mentioning it, and its true that its been a bit confusing how Marathon has been dealing with ports/services. I will take a new look into it I think! 👍
