### ISSUE TITLE
Filter mesos apps

### ISSUE THREAD

**Issue by Krassi10** [martensson/nixy#3]
Hi, i've just tested nixy, works great, thank you.

Do you plan implementing a filter possibility on the apps? We have some apps which we do not want to proxy to the outside world. We also have some productive web containers and some internal ones and would like to be able to use some marathon labels or other environment variables to dinstinguish between those (and run two different instances of naxi of course).

Thanks
Krassi

**Comment by martensson** [comment]
Hi @Krassi10!

I already have this in the works, and thinking of the easiest way solve it. Right now its actually possible todo it and not that difficult, just add any label to your apps and check if it exists inside your template. If it does exist just add a small acl snippet that fits your environment to that app with the nginx allow/deny rules. Kind of the great benefit of using nginx and templating.

I am currently a bit busy this week, but plan to add some documentation and examples for this next week ;)

Regards,
Benjamin

**Comment by Krassi10** [comment]
Hi Benjamin,

great, thanks. I'm not very used to go templating so looking forward to the documentation. Yes, nginx is best, that's why i prefer nixy. Until now i'm working with marathon, registrator, consul, consul-template and haproxy. nixy will simplifiy my workflow...

Have a nice weekend.

Regards
Krassi

**Comment by martensson** [comment]
@Krassi10 please check https://github.com/martensson/nixy#template for an example of how to add some ACL rules your app. Please tell me if its OK.

**Comment by Krassi10** [comment]
Thank you! Iwas able to get it running. Now i'm filtering dmz servers with
{{range $id, $app := .Apps}}{{if .Labels.dmz}}
and it works. Would be nice if the label(s) name(s) could be defined in the config file.

**Comment by martensson** [comment]
Great, but I am not sure I understand what you mean with the label name?

**Comment by Krassi10** [comment]
Sorry, i'll try to explain. Your approach with ACL is different, in my opinion another requirement but also very good. Setting who can access which service is really nice and handy.

What i wanted to achieve (and done :-) is to eliminate all mesos services i do not want to have listed in the nginx config. I've done this by setting the mesos label dmz to 1 and filtering it with
{{if .Labels.dmz}}
in the template file. Now only services with the label dmz (whatever the value is) are taken over to the nginx config file. I plan to implement several nixy instances.

It would be nice if we could add a config variable inside of nixy.toml. If this variable isn't empty the services could be filtered by this label value. Don't know if this makes sense for all use cases...

One advantage would be using a single nginx.tmpl file for external and internal services, just the nginx.toml would be different. Setting/Replacing the value in the toml could then be done based on the hostname where nixy runs on (via puppet/chef/salt/batch/whatever). Or, if in a container, given by a label or parameter for a nixy docker image.

**Comment by martensson** [comment]
Ahh I see, and I can see the benefit on one part but I believe its one of these options that should be inside the template. It is possible to use puppet/salt/chef to configure the template and change which services should be active that way instead.

I try to keep nixy as simple as possible and only add the options that really are necessary and not possible to add via the template itself. I hope it makes sense :smiley:

**Comment by Krassi10** [comment]
Absolutely fine for me, thanks.

I've discovered another usage case where i'm experiencing problems. i can only "submit" one subdomain per container. Adding several subdomains as labels results in a
nginx: [emerg] invalid number of arguments in "upstream" directive
because the upstream name depends on this label also.

e.g.
label: "subdomain": "host1 host2 host3",

upstream host1 host2 host3 {

**Comment by martensson** [comment]
That is definitely a useful feature, I will look into that the coming days. :+1:

**Comment by Krassi10** [comment]
Thanks.

**Comment by martensson** [comment]
Feature is now added, check latest release. Just remember to update the template to the new one as well.

**Comment by martensson** [comment]
Closing this issue, please open a new one if there is anything else.
