### ISSUE TITLE
App Health Check Path

### ISSUE THREAD

**Issue by dharm187** [martensson/nixy#31]
Hello,

Is there any way to get the application health check path (deployed in marathon) in nixy?

I changed the nixy code to get it and am able to get it successfully. But is there is any other way to get it?

Thanks

**Comment by martensson** [comment]
Hi @dharm187, 
Currently its not possible, but its definitely not a difficult feature to add. 
Could I just ask in what kind of scenario you would need it?

**Comment by dharm187** [comment]
Hi @martensson,

Thanks a lot for your reply.

We have lots of Spring boot application which are deployed using marathon. To check the health of application we put the context root of those application under marathon.

Now when we access them (after nixy gave use the URL), we have to put the url as below:
servername:port/apphealthcheckpath

If we had the healthcheck path exposed, we could have used it in template.

It could be a handy feature to have in the scenarios when we have java based application.

Thanks

**Comment by martensson** [comment]
Now added to commit https://github.com/martensson/nixy/commit/d997a0e0852b7e3b458eaec295e930b5b80c36d2. I will make a new release in a moment :)
