### ISSUE TITLE
Templates can lead to bad config

### ISSUE THREAD

**Issue by tadanki** [martensson/nixy#32]
Hi, 
We have noticed that in some instances we can end up with stale config being served by Nginx.
On digging further we see that in the upstream block in the candidate nginx.conf that is written out, is missing a host and just reads 
server :<port>
This seems to happen when the .Host variable in the .Tasks struct is empty.
Is it possible to add some simple filtering to nixy to ensure that tasks are only valid if they have both .Host and .Ports non empty? 
We tried to suppress them in templating but that can potentially lead to an empty upstream block which is also invalid. Can't seem to find a clean way to do it in templating. 
Thoughts?

**Comment by martensson** [comment]
Hi @tadanki! Sorry for the delay, and I will look into it.
Just a question, what kind of app are you deploying that is missing even a host? Did not know that was even possible 😕 . So if you have a snippet of the app in question it would be great! 
But the fix should be really easy, already have a check if ports are set, just need to add another for the host field as well.

**Comment by martensson** [comment]
You can now also try the latest release including the fix.

**Comment by martensson** [comment]
I am closing this issue now, please report if its still a problem!
