### ISSUE TITLE
Question about port definition 

### ISSUE THREAD

**Issue by Alien2150** [martensson/nixy#35]
Hey, 

I like your software pretty much. I was just curious why the name field in the port definition was left out. I could use it for some use case. Is it intended? If not I would be willing to addd a PR to that. 

With best regards

**Comment by martensson** [comment]
Hi @Alien2150 ! Sorry for the delay but I just pushed a fix for it. Will soon make a new tag/release with the fix included 😃 
PS: Glad you like nixy btw! 👍
