### ISSUE TITLE
Apps with same subdomain aren't detected by nixy

### ISSUE THREAD

**Issue by naman** [martensson/nixy#36]
Cool app by the way, thanks. Makes life really easy for us.

I am testing a Blue-green/AB deployment where two (distinct) apps have the same `NIXY_REALM` and `subdomain` tags, but nixy only lists tasks running for just one app. Is this the normal behaviour or am I missing something?

nixy version: 
```
version: 0.13.0
commit: 776381f991adb5fb8f91cdde0f170ba8704121fa
date: 2017-11-13T12:56:12Z
```

Thanks

**Comment by martensson** [comment]
Hi @naman! Sorry for the great delay. 
But I think this is a normal behavior, by default nixy will try to avoid "merging" tasks for apps using the same subdomain label. This is to avoid strange cases where people try to deploy two different apps using the same subdomain, this would also cause some nginx duplicate errors.

Normally its marathon that should take care of handling the rolling updates and inform nixy when the new tasks are available. Unfortunately as far as I know its not possible to do blue-green deployments with marathon, unless its a new feature added.

We could of course do some workaround using nixy by combining two apps as you suggest, but it would have to be well thought and tested. An idea is that you simply switch the subdomain label of the two apps when you need to make the switch.

Please tell me if this is still a problem or if you managed to find a solution!

**Comment by naman** [comment]
Hi @martensson! Sorry for the delay from my side. Yes, I read the code where nixy checks for duplicates having the same subdomain label. I was curious if this behaviour was being correctly handled by nixy. For now, our scale is really small to test blue-green deployments right now.

Thanks for all the help!

**Comment by martensson** [comment]
Thanks for the reply! 👍
