### ISSUE TITLE
Pass Statsd to nginx.tmpl

### ISSUE THREAD

**Issue by dylanmei** [martensson/nixy#5]
I have an nginx server with the [nginx statsd module](https://github.com/zebrafishlabs/nginx-statsd) built in. It would be very convenient and harmonious if the same statsd addr I pass to nixy can make its way to the nginx configuration.

For example, an `nginx.tmpl` file.

```
http {
    add_header X-Proxy {{ .Xproxy }} always;
    statsd_server {{ .Statsd }};
    server { ... }
}
```

I can see changing `json:"-"` to `json:",omitempty"` or removing the constraint altogether. What do you think?

**Comment by martensson** [comment]
Hi @dylanmei,
Never heard of the statsd module before, but it definitely looks nice.
I just made a new release that adds the statsd variable, now that I see it can actually be useful inside the template as well :+1: 

https://github.com/martensson/nixy/releases/tag/v0.4.10

**Comment by dylanmei** [comment]
Thanks @martensson. However, I don't see the change in the github web ui or in the `github.com/martensson/nixy/archive/v0.4.10.zip` release. Have I missed something?

**Comment by martensson** [comment]
Hmm not sure why, Its been pushed to master and part of the last release? :confused: 
https://github.com/martensson/nixy/blob/c5fb3cd5372cb489b4b24686fb4e69f9b555601f/nixy.go#L37

edit: thinking back its actually possible you checked the repo before I pushed it, in this case I am sorry for that!
